export const homeContent = {
  seo: {
    title: 'Crealize - Transforming Imagination into Reality',
    description: 'Redefining the possibilities of creative realization with Web3 × Gamification × AI.',
  },
  slogan: ['Transforming', 'Imagination', 'into', 'Reality'],
  logo: {
    src: '/image/Crealizelogo1.png',
    alt: 'Crealize Logo',
    width: 90,
    height: 48,
  },
  brandName: 'Crealize',
  sections: [
    {
      id: 'vision',
      title: 'VISION',
      content: [
        '把創意轉化為現實',
        'Crealize 是由 "Creative" × "Realize" 所組成的名字',
        '「創意若不被實現，只是空談。」',
        '擅長將點子從 0 執行至 1，經過驗證、反覆打磨，最終變為可觸及的數位產品',
        'Web3 × 遊戲化 × AI × 價值網路',
      ],
    },
    {
      id: 'projects',
      title: 'PROJECTS',
      content: [
        '標題：社群導向的創作者交易平台',
        '智能合約 × 第三方 KYC，打造可信賴交易環境',
        '結合區塊鏈智能合約與合規身份驗證（KYC）機制，確保交易雙方資訊透明、流程安全。',
        '按讚與關注，即可影響市場價格',
        '粉絲的每一次按讚與關注，將轉化為可量化的價值指標，直接影響創作者在平台上的估值與股權價格。',
        '開放式評價系統 × 社群共治機制',
        '評價權開放給所有社群成員參與，避免黑箱操作，建立透明、公正的社群治理模式。',
        '投票參與決策，影響創作者市值',
        '用戶可透過投票表達支持，進一步形塑創作者的市值與曝光機會，讓粉絲參與不僅有感，更具影響力。',
        '手續費回饋 × 粉絲經濟閉環',
        '每一筆交易產生的部分手續費，將回饋給對應的創作者，促進創作者與粉絲之間的雙向成長與長期連結。',
        '平台合規進行中',
        '目前平台已在新加坡進行合規審查，積極配合法規，以確保日後的國際化營運穩健合法。',
        '標題：GameFi 策略遊戲：Mars2049',
        'Play-to-Earn 遊戲機制 × 區塊鏈資產經濟',
        '結合建設、探索與競爭玩法，讓玩家透過遊戲任務賺取虛擬資產，實現娛樂與收益並進。',
        'Telegram Mini App 全球封測進行中',
        '目前主打遊戲《Mars2049》已於 Telegram Mini App 上開啟全球封測：',
        '官方網站：https://www.mars2049.online/',
        '體驗入口：https://t.me/Mars2049_Bot/Mars2049?startapp=1ARn69BN',
        '無須下載，即點即玩，為全球玩家提供輕量流暢的上手體驗。',
        '未來導入代幣經濟 × 多鏈資產擴展',
        '遊戲預計將推出專屬代幣，並支援多鏈資產互通，擴展整體經濟體系與收藏價值。',
        '標題：AI 虛擬影響者與社群經營工具',
        '整合 x.com API，掌握最新社群脈動',
        'AI 將即時擷取來自 x.com（前 Twitter）的熱搜趨勢與新聞內容，助你快速掌握話題走向。',
        '自動生成評論 × 精準行銷建議',
        '搭載自然語言處理模型，可為品牌與社群主提供個性化、即時的行銷文案與互動建議。',
        'AI 音樂人 × 聲音角色虛擬化',
        '透過語音合成與 AI 編曲技術，生成虛擬創作者形象，支援演唱、發言與互動應對。',
        '企業代言人 × 社群操盤角色',
        '這些 AI 虛擬角色不僅是工具，更能作為品牌的代表，參與行銷推廣與社群活動，成為企業專屬的虛擬資產與數位人物形象。',
      ],
    },
    {
      id: 'tech',
      title: 'TECH PHILOSOPHY',
      content: [
        '去中心化 × 前端驅動',
        '低維運、高穩定、可擴展',
        '靜態前端部署實現零伺服器、零維護費',
        '區塊鏈整合，實現去中心化身份驗證與資產管理',
        'AI 多語翻譯系統：善用 Google Apps Script 搭配 GPT搭建入門後台',
        '低成本、高自由的開發模型',
      ],
    },
    {
      id: 'join',
      title: 'JOIN US',
      content: [
        '全球招募中，支援全遠端工作',
        '總部設於東京',
        '完全自由的工作環境，專注成果，不看打卡',
        '我們歡迎工程師、設計師、PM、創意人、遊戲製作人、Web3 領域專才',
      ],
    },

  ],
}; 